# Regresión lineal en Python

## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [8]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [9]:
mainpath = "C:/Users/dguai/Documents/Courses/Machine Learning Data Science en Python/Practicas/Repositorios/Datasets"
data = pd.read_csv(mainpath + "/" + "Ads/Advertising.csv")

In [10]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [11]:
X = data[feature_cols]
Y = data["Sales"]

In [12]:
estimator = SVR(kernel = "linear")
selector = RFE(estimator, 2, step = 1)
selector = selector.fit(X,Y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [13]:
selector.support_

array([ True,  True, False])

In [14]:
selector.ranking_

array([1, 1, 2])

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
X_pred = X[["TV", "Radio"]]

In [17]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [18]:
lm.intercept_

2.921099912405138

In [19]:
lm.coef_

array([0.04575482, 0.18799423])

In [20]:
lm.score(X_pred, Y) # R**2 ajustado

0.8971942610828957