# El método de K-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.09257951, 0.14709189, 0.50210785],
       [0.154641  , 0.69573836, 0.69277781],
       [0.71185078, 0.73098615, 0.4116659 ],
       [0.74267672, 0.7474862 , 0.45740817],
       [0.59011774, 0.76883696, 0.68812785],
       [0.5766859 , 0.64346692, 0.01385741],
       [0.87584821, 0.64290416, 0.34322297],
       [0.66927525, 0.02705339, 0.21765294],
       [0.48333195, 0.11324897, 0.02619194],
       [0.30788944, 0.47497284, 0.20368814],
       [0.1482226 , 0.68847245, 0.43275044],
       [0.24517319, 0.25619579, 0.89613001],
       [0.43614727, 0.5505621 , 0.7661647 ],
       [0.5039479 , 0.93866271, 0.63020447],
       [0.7025978 , 0.82198222, 0.01404713],
       [0.97034719, 0.63411264, 0.21929821],
       [0.53332844, 0.91034866, 0.62059251],
       [0.80181505, 0.88376836, 0.41975077],
       [0.79666978, 0.03715232, 0.50790056],
       [0.44504055, 0.02791319, 0.94047367],
       [0.22960612, 0.16134287, 0.81980823],
       [0.76838829, 0.46803908, 0.10060925],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.1482226 , 0.68847245, 0.43275044],
       [0.66927525, 0.02705339, 0.21765294]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
clusters = vq(data, clust_centers)
clusters

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
        0, 0, 1, 1, 0, 0, 1, 0]),
 array([0.54863423, 0.26020803, 0.5656224 , 0.59788488, 0.51666952,
        0.60089738, 0.66159837, 0.        , 0.28046729, 0.35148986,
        0.        , 0.64107968, 0.46161125, 0.47762302, 0.70743847,
        0.67761933, 0.48251446, 0.68227016, 0.31713568, 0.75680364,
        0.65901639, 0.46689506, 0.43880086, 0.48593066, 0.38805331,
        0.74667475, 0.43535545, 0.7085811 , 0.35681743, 0.3967702 ]))

In [6]:
from scipy.cluster.vq import kmeans

In [7]:
kmeans(data, clust_centers)

(array([[0.43136919, 0.59056974, 0.48882123],
        [0.75631257, 0.28632124, 0.37283515]]),
 0.4082980263214259)

In [8]:
kmeans(data, 2)

(array([[0.36458175, 0.29862033, 0.52662652],
        [0.7398001 , 0.70690585, 0.36276798]]),
 0.35449485723935165)